---
- name: Infoblox Member Configuration
  hosts: localhost
  vars:
    nios_provider:
      host: 10.36.118.2
      username: cloudadmin
      password: admin

  connection: local
  tasks:
    - name: Create Nios Host Record
      infoblox.nios_modules.nios_host_record:
        name: host.ansibletestzone.com
        view: ansibleDnsView
        ipv4addrs:
          - ipv4addr: 192.168.11.251
        comment: Created with Ansible
        state: present
        provider: "{{ nios_provider }}"
